import { useState } from 'react'
import { createPortal } from 'react-dom'
import { UNITS, STATEMENTS, fmt } from '../data/financialData'
import './FinancialStatements.css'

function DocIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--lime)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
      <line x1="16" y1="13" x2="8" y2="13" />
      <line x1="16" y1="17" x2="8" y2="17" />
    </svg>
  )
}

function addDays(mdy, days) {
  const [m, d, y] = mdy.split('/').map(Number)
  const dt = new Date(y, m - 1, d + days)
  return `${dt.getMonth() + 1}/${dt.getDate()}/${dt.getFullYear()}`
}

function StatementViewer({ unit, statement, onClose }) {
  return createPortal(
    <div className="fst-panel">
      <div className="fst-panel__header">
        <span className="fst-panel__title">{statement.filename}</span>
        <button className="fst-panel__close" onClick={onClose} aria-label="Close">×</button>
      </div>
      <div className="fst-panel__body">
        <div className="fst-doc">
          <p className="fst-doc__hoa">Cardinal Hills HOA</p>
          <h3 className="fst-doc__heading">Monthly Statement — {statement.month}</h3>
          <p className="fst-doc__meta">{unit.label} · ACC#: {unit.account}</p>
          <div className="fst-doc__divider" />

          <div className="fst-doc__row">
            <span>Statement Date</span>
            <span>{statement.date}</span>
          </div>
          <div className="fst-doc__row">
            <span>Payment Due Date</span>
            <span>{addDays(statement.date, 10)}</span>
          </div>
          <div className="fst-doc__divider" />

          <div className="fst-doc__row">
            <span>Total Charges</span>
            <span>{fmt(statement.amount)}</span>
          </div>
          <div className="fst-doc__row fst-doc__row--total">
            <span>Amount Due</span>
            <span>{fmt(statement.amount)}</span>
          </div>

          <p className="fst-doc__footer">
            Generated by Cardinal Hills HOA management on {statement.date}. Contact the HOA office with any
            questions regarding this statement.
          </p>
        </div>
      </div>
    </div>,
    document.querySelector('.phone-frame') || document.body
  )
}

export default function FinancialStatements({ unitId }) {
  const unit = UNITS.find(u => u.id === unitId) || UNITS[0]
  const statements = STATEMENTS[unit.id] || []
  const [selected, setSelected] = useState(null)

  return (
    <div className="screen fst-screen">
      <h1 className="fst-title">Statements</h1>
      <p className="fst-subtitle">{unit.label} · ACC#: {unit.account}</p>

      <div className="fst-list">
        {statements.map(s => (
          <button key={s.filename} className="fst-row" onClick={() => setSelected(s)}>
            <span className="fst-row__icon"><DocIcon /></span>
            <div className="fst-row__text">
              <span className="fst-row__label">{s.month} Statement</span>
              <span className="fst-row__sub">Issued {s.date}</span>
            </div>
            <span className="fst-row__amount">{fmt(s.amount)}</span>
          </button>
        ))}
      </div>

      {selected && (
        <StatementViewer unit={unit} statement={selected} onClose={() => setSelected(null)} />
      )}
    </div>
  )
}
